spring:

##Postgres##
  #datasource:
   # url: jdbc:postgresql://localhost:5432/postgres
   # username: postgres


    # password: cms@springfive

   # driver-class-name: org.postgresql.Driver
 # jpa:
  #  show-sql: true
 # generate-ddl: true
##Postgres##


##MongoDB##
# This section is for MongoDB
  data:
    mongodb:
      database: cms
      host: localhost
      port: 27017

## MongoDB##